apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon
spec:
  selector:
    matchLabels:
      app: hackazon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: registry.lab.livefire.dev/vcnlivefire/vulnerableapps/hackazon
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hackazon-lb
  labels:
    app: hackazon
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.110.101
  ports:
  - port: 80
    nodePort: 30537
  selector:
    app: hackazon
