apiVersion: v1
kind: Namespace
metadata:
  name: vulnapps-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: vulnapps-dev
spec:
  selector:
    matchLabels:
      app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: registry.lab.livefire.dev/vcnlivefire/vulnapps/drupal:8.5.1
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: k8s-dev-node-01
