apiVersion: v1
kind: Pod
metadata:
      name: curl
      labels:
          app: web
spec:
     containers:
     - name: source
       image: quay.io/cilium/alpine-curl
       command: ["sh", "-c", "while true; do sleep 3600; done"]
     dnsPolicy: "None"
     dnsConfig:
       nameservers:
       - 192.168.110.10
