- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: false
  vars_files:
    - static_vars.yml
    - user_defined_vars.yml
  tasks:
    - name: Create IP Pools
      vmware.ansible_for_nsxt.nsxt_policy_ip_pool:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        pool_static_subnets: "{{ item.subnets }}"
        state: "{{ state }}"
      with_items:
        - "{{ ip_pools  }}"
