- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - static_vars.yml
    - user_defined_vars.yml
  tasks:
    - name: Create Transport Node Profiles
      vmware.ansible_for_nsxt.nsxt_transport_node_profiles:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        state: "{{ state }}"
      with_items:
        - "{{ transport_node_profiles }}"

    - name: Attach Transport node profile to collapsed cluster
      vmware.ansible_for_nsxt.nsxt_transport_node_collections:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{transport_node_profiles[0].display_name }}"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections Hosts"
        compute_manager_name: "{{compute_managers[0].display_name}}"
        cluster_name: "{{ vcenter.cluster }}"
        transport_node_profile_name: "{{transport_node_profiles[0].display_name}}"
        state: present

    - name: Pause for 10 minutes so that Host TN are Ready (!!!DO NOT SKIP!!!)
      pause:
        minutes: 10

