- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no
  vars_files:
    - static_vars.yml
    - user_defined_vars.yml
  tasks:
    - name: Create Edge Transport Nodes
      vmware.ansible_for_nsxt.nsxt_transport_nodes:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: "{{ state }}"
      async: 2000
      poll: 0
      with_items:
        - "{{ transport_nodes }}"

    - name: Pause for 15 minutes so that Edge Nodes are Ready (!!!DO NOT SKIP!!!)
      pause:
        minutes: 15

    - name: Add edge cluster
      vmware.ansible_for_nsxt.nsxt_edge_clusters:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        cluster_profile_bindings:
        - profile_name: "nsx-default-edge-high-availability-profile"
          resource_type: "EdgeHighAvailabilityProfile"
        members: "{{ item.members }}"
        state: "{{ state }}"
      with_items:
        - "{{ edge_clusters }}"
