AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lRZHV3Z0J1TDZOcHhFSkxaTkpZN1pHekFOQmdrcWhraUc5dzBCQVFVRkFEQkkKTVJVd0V3WUtDWkltaVpQeUxHUUJHUllGYkc5allXd3hGREFTQmdvSmtpYUprL0lzWkFFWkZnUmpiM0p3TVJrdwpGd1lEVlFRREV4QkRUMDVVVWs5TVEwVk9WRVZTTFVOQk1DQVhEVEUwTURNd05qRTNNamcxTVZvWUR6SXdOalF3Ck16QTJNVGN6T0RVd1dqQklNUlV3RXdZS0NaSW1pWlB5TEdRQkdSWUZiRzlqWVd3eEZEQVNCZ29Ka2lhSmsvSXMKWkFFWkZnUmpiM0p3TVJrd0Z3WURWUVFERXhCRFQwNVVVazlNUTBWT1ZFVlNMVU5CTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBclcyTTJ5SUNXbjFJUE5zekxCcXFWaldabGtwMlR0cTJ4eFlnCkM2YTRzd0lTaW9Dc2R2cnhFT1Azd1pmRFlKRjFMUmpaYXc5THJxa1lRdExRQW9JR0JDRHJRM1RWdlpVK1BtdEMKYWtReXpZb2U2K0hqYjNoZmM3RkJYanFmckVZM0RNc2V1NjlDTWVYcVVXNHZoeVJ2Y3RRYURkYmozWjkxKzV2ZApJa3hxMFB3c3lpQmFIcjhhNkg4RWd5WE9ZbDFJMmhwSTRWaGczaitoMzNmVWJaZVpIV20vc2Y4bGRmalRmbVVJCnBFdnlnenRMNEFuVHQ1VVFiNVNYRDBkc2lyZS93Tmg3c3lZUFFvTW5PL0hqSFlTSDhFcFFsZkVnYWRmV0NIdU0KYWkxdmc4NTNSRGNuakpFZ3l3eEFNTnE0WEUrU1JBRUN2TjZWS2xkUk9WU1AzMnFxaFFJREFRQUJvMUV3VHpBTApCZ05WSFE4RUJBTUNBWVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVckxIOHorbnhZSm5aCjdLdGJWYWRDc1Y4V0toNHdFQVlKS3dZQkJBR0NOeFVCQkFNQ0FRQXdEUVlKS29aSWh2Y05BUUVGQlFBRGdnRUIKQUFNZm9TSnFTNkpiVEgxaklmMFNCVWRYZkxWa0RWWEh3bEZ0WWFRV3B3NndSR3FNSGJkRXZhWkdHZzl5NVVXdApINlZyNEpSOEtHWlkxeGpUK0Q4WkM5dDNWQ3V5R1ZZbE1WdEU4UkE0em9zYUVDODc3UDJjOFRFb0RuaVV0TG5mCkZpZmtweEZsbllXWDRTL2sxcDJRK2VsSVVwc1MrNjNFeC9wSFlqbGVCZEl2TmVZbHREZXlZMnRKMkl2VFR4bXYKZzR1MWhITjhJNTZiQ3JtbE95MUdrTm9aVCsxVUFuV250VWVnWCs0dnVZdXYzTDU4MHBET3FmeEtpNmljZWROUAplVDJtYWE2aXVxK1dJbW5zNjRtR3NHdlc3c2RrQWVvOEFMTVlsaHV5ODZPSkZjK2o4djZocTNabHI4cGEyU1VaCkU3Y1krbldlcm9HR2QzT1VIdzM5ckdnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
AVI_CLOUD_NAME: vcsa-01a
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
AVI_CONTROL_PLANE_NETWORK: ov-tkg-vip
AVI_CONTROL_PLANE_NETWORK_CIDR: 172.16.110.0/24
AVI_CONTROLLER: avi-01a.corp.local
AVI_DATA_NETWORK: ov-tkg-vip
AVI_DATA_NETWORK_CIDR: 172.16.110.0/24
AVI_ENABLE: "true"
AVI_LABELS: |
    'avi': 'np-enabled'
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_CIDR: 172.16.110.0/24
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_NAME: ov-tkg-vip
AVI_MANAGEMENT_CLUSTER_SERVICE_ENGINE_GROUP: Default-Group
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 172.16.110.0/24
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: ov-tkg-vip
AVI_PASSWORD: <encoded:Vk13YXJlMSE=>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_ANNOTATIONS: 'location:,description:'
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: vsphere-mgmt
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: ldap
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: administrator@corp.local
LDAP_BIND_PASSWORD: <encoded:Vk13YXJlMSE=>
LDAP_GROUP_SEARCH_BASE_DN: dc=corp,dc=local
LDAP_GROUP_SEARCH_FILTER: member=o
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: ""
LDAP_HOST: controlcenter.corp.local:636
LDAP_ROOT_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lRZHV3Z0J1TDZOcHhFSkxaTkpZN1pHekFOQmdrcWhraUc5dzBCQVFVRkFEQkkKTVJVd0V3WUtDWkltaVpQeUxHUUJHUllGYkc5allXd3hGREFTQmdvSmtpYUprL0lzWkFFWkZnUmpiM0p3TVJrdwpGd1lEVlFRREV4QkRUMDVVVWs5TVEwVk9WRVZTTFVOQk1DQVhEVEUwTURNd05qRTNNamcxTVZvWUR6SXdOalF3Ck16QTJNVGN6T0RVd1dqQklNUlV3RXdZS0NaSW1pWlB5TEdRQkdSWUZiRzlqWVd3eEZEQVNCZ29Ka2lhSmsvSXMKWkFFWkZnUmpiM0p3TVJrd0Z3WURWUVFERXhCRFQwNVVVazlNUTBWT1ZFVlNMVU5CTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBclcyTTJ5SUNXbjFJUE5zekxCcXFWaldabGtwMlR0cTJ4eFlnCkM2YTRzd0lTaW9Dc2R2cnhFT1Azd1pmRFlKRjFMUmpaYXc5THJxa1lRdExRQW9JR0JDRHJRM1RWdlpVK1BtdEMKYWtReXpZb2U2K0hqYjNoZmM3RkJYanFmckVZM0RNc2V1NjlDTWVYcVVXNHZoeVJ2Y3RRYURkYmozWjkxKzV2ZApJa3hxMFB3c3lpQmFIcjhhNkg4RWd5WE9ZbDFJMmhwSTRWaGczaitoMzNmVWJaZVpIV20vc2Y4bGRmalRmbVVJCnBFdnlnenRMNEFuVHQ1VVFiNVNYRDBkc2lyZS93Tmg3c3lZUFFvTW5PL0hqSFlTSDhFcFFsZkVnYWRmV0NIdU0KYWkxdmc4NTNSRGNuakpFZ3l3eEFNTnE0WEUrU1JBRUN2TjZWS2xkUk9WU1AzMnFxaFFJREFRQUJvMUV3VHpBTApCZ05WSFE4RUJBTUNBWVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVckxIOHorbnhZSm5aCjdLdGJWYWRDc1Y4V0toNHdFQVlKS3dZQkJBR0NOeFVCQkFNQ0FRQXdEUVlKS29aSWh2Y05BUUVGQlFBRGdnRUIKQUFNZm9TSnFTNkpiVEgxaklmMFNCVWRYZkxWa0RWWEh3bEZ0WWFRV3B3NndSR3FNSGJkRXZhWkdHZzl5NVVXdApINlZyNEpSOEtHWlkxeGpUK0Q4WkM5dDNWQ3V5R1ZZbE1WdEU4UkE0em9zYUVDODc3UDJjOFRFb0RuaVV0TG5mCkZpZmtweEZsbllXWDRTL2sxcDJRK2VsSVVwc1MrNjNFeC9wSFlqbGVCZEl2TmVZbHREZXlZMnRKMkl2VFR4bXYKZzR1MWhITjhJNTZiQ3JtbE95MUdrTm9aVCsxVUFuV250VWVnWCs0dnVZdXYzTDU4MHBET3FmeEtpNmljZWROUAplVDJtYWE2aXVxK1dJbW5zNjRtR3NHdlc3c2RrQWVvOEFMTVlsaHV5ODZPSkZjK2o4djZocTNabHI4cGEyU1VaCkU3Y1krbldlcm9HR2QzT1VIdzM5ckdnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
LDAP_USER_SEARCH_BASE_DN: cn=Users,dc=corp,dc=local
LDAP_USER_SEARCH_FILTER: cn=O
LDAP_USER_SEARCH_NAME_ATTRIBUTE: sAMAccountName
LDAP_USER_SEARCH_USERNAME: sAMAccountName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_CONTROL_PLANE_ENDPOINT: ""
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /Site-A
VSPHERE_DATASTORE: /Site-A/datastore/Site-A-NFS
VSPHERE_FOLDER: /Site-A/vm/tkg
VSPHERE_INSECURE: "true"
VSPHERE_NETWORK: /Site-A/network/ov-tkg
VSPHERE_PASSWORD: <encoded:Vk13YXJlMSE=>
VSPHERE_RESOURCE_POOL: /Site-A/host/Cluster-01/Resources/tkg
VSPHERE_SERVER: vcsa-01a.corp.local
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDp+tog6hS4M5EpTLk80oTzcEPer2bty8xO7t2Gr8/T91IporegE2xtY2KyX8veddlAVWzYyl6MTmVHdcPVSILNdwPMS3cRnrle4txf51BH41qq+itA/afntoAPm24XPQNBIroCf9WeN5yQI5vynXKxBmww2KTzZjLnOXhwPr7e0++UCE9tC/2KtBCajej9/5WJlRVX3nzHCASMBWGi0Z6KCrmOoaB02GTywt3+IVABo5q0Q3Bjly8LLOixTzuLqiE6Cap0yYcKj9SfhSFNrmkW+6JSWompGRF/L9h79km8stbh9yrQGGec3+WCdeGG4ABm9ZNqPwCarRAi+W8FdT8d+M9svE2e5S/dGMbQLmVD7CWOBK5XXh1OMUo4eQQ/tKvBDmBgB6wFHQLRaolAwqaFJ9ZFwpVzJaeF1zBqpTG037tST4DzwyWQt5pLwAkNVFgcV2IEb7JfIUyMvYuXXdVfVAjufkhPD593GfKgz2ZnhfvZgMZ3u9wJKZZy+Y+l2Rpw8gofwEv8RmwFAK+EZGNrd8oZJtY5PAS9tuodmM4eSg4xT7hhNIzJeZ/14LfPcrUUYpcBLWr7AX8lDbNnBzLi1TSRWnQNMgVoFYg4BEGUxWSzpC83vtrYxLAeJVaFfVQcx+qcJquhvo2ZcS+BW9m2dUgyUg9wEwcRHeHsL2BEOQ== livefire@ubuntu-utils
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_WORKER_DISK_GIB: "20"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_WORKER_NUM_CPUS: "2"
WORKER_ROLLOUT_STRATEGY: ""
