INFRASTRUCTURE_PROVIDER: vsphere
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
CLUSTER_ANNOTATIONS: 'location:,description:'
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: vsphere-wld
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "false"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
CONTROL_PLANE_MACHINE_COUNT: "1"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: ""
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /Site-A
VSPHERE_DATASTORE: /Site-A/datastore/Site-A-NFS
VSPHERE_FOLDER: /Site-A/vm/tkg
VSPHERE_INSECURE: "true"
VSPHERE_NETWORK: /Site-A/network/ov-tkg
VSPHERE_PASSWORD: <encoded:Vk13YXJlMSE=>
VSPHERE_RESOURCE_POOL: /Site-A/host/Cluster-01/Resources/tkg
VSPHERE_SERVER: vcsa-01a.corp.local
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDp+tog6hS4M5EpTLk80oTzcEPer2bty8xO7t2Gr8/T91IporegE2xtY2KyX8veddlAVWzYyl6MTmVHdcPVSILNdwPMS3cRnrle4txf51BH41qq+itA/afntoAPm24XPQNBIroCf9WeN5yQI5vynXKxBmww2KTzZjLnOXhwPr7e0++UCE9tC/2KtBCajej9/5WJlRVX3nzHCASMBWGi0Z6KCrmOoaB02GTywt3+IVABo5q0Q3Bjly8LLOixTzuLqiE6Cap0yYcKj9SfhSFNrmkW+6JSWompGRF/L9h79km8stbh9yrQGGec3+WCdeGG4ABm9ZNqPwCarRAi+W8FdT8d+M9svE2e5S/dGMbQLmVD7CWOBK5XXh1OMUo4eQQ/tKvBDmBgB6wFHQLRaolAwqaFJ9ZFwpVzJaeF1zBqpTG037tST4DzwyWQt5pLwAkNVFgcV2IEb7JfIUyMvYuXXdVfVAjufkhPD593GfKgz2ZnhfvZgMZ3u9wJKZZy+Y+l2Rpw8gofwEv8RmwFAK+EZGNrd8oZJtY5PAS9tuodmM4eSg4xT7hhNIzJeZ/14LfPcrUUYpcBLWr7AX8lDbNnBzLi1TSRWnQNMgVoFYg4BEGUxWSzpC83vtrYxLAeJVaFfVQcx+qcJquhvo2ZcS+BW9m2dUgyUg9wEwcRHeHsL2BEOQ== livefire@ubuntu-utils
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
WORKER_MACHINE_COUNT: "2"
ENABLE_MHC_CONTROL_PLANE: false
ENABLE_MHC_WORKER_NODE: false

#! ---------------------------------------------------------------------
#! NSX specific configuration for enabling NSX routable pods
#! ---------------------------------------------------------------------

# NSXT_POD_ROUTING_ENABLED: false
# NSXT_ROUTER_PATH: ""
# NSXT_USERNAME: ""
# NSXT_PASSWORD: ""
# NSXT_MANAGER_HOST: ""
# NSXT_ALLOW_UNVERIFIED_SSL: false
# NSXT_REMOTE_AUTH: false
# NSXT_VMC_ACCESS_TOKEN: ""
# NSXT_VMC_AUTH_HOST: ""
# NSXT_CLIENT_CERT_KEY_DATA: ""
# NSXT_CLIENT_CERT_DATA: ""
# NSXT_ROOT_CA_DATA: ""
# NSXT_SECRET_NAME: "cloud-provider-vsphere-nsxt-credentials"
# NSXT_SECRET_NAMESPACE: "kube-system"

#! ---------------------------------------------------------------------
#! Antrea CNI configuration
#! ---------------------------------------------------------------------
# ANTREA_NO_SNAT: false
# ANTREA_DISABLE_UDP_TUNNEL_OFFLOAD: false
# ANTREA_TRAFFIC_ENCAP_MODE: "encap"
# ANTREA_EGRESS_EXCEPT_CIDRS: ""
ANTREA_NODEPORTLOCAL_ENABLED: true
ANTREA_NODEPORTLOCAL_PORTRANGE: 61000-62000
# ANTREA_PROXY_ALL: false
# ANTREA_PROXY_NODEPORT_ADDRS: ""
# ANTREA_PROXY_SKIP_SERVICES: ""
# ANTREA_PROXY_LOAD_BALANCER_IPS: false
ANTREA_FLOWEXPORTER_COLLECTOR_ADDRESS: "flow-aggregator.flow-aggregator.svc:4739:tls"
ANTREA_FLOWEXPORTER_POLL_INTERVAL: "5s"
ANTREA_FLOWEXPORTER_ACTIVE_TIMEOUT: "30s"
ANTREA_FLOWEXPORTER_IDLE_TIMEOUT: "15s"
# ANTREA_KUBE_APISERVER_OVERRIDE:
# ANTREA_TRANSPORT_INTERFACE:
# ANTREA_TRANSPORT_INTERFACE_CIDRS: ""
# ANTREA_MULTICAST_INTERFACES: ""
# ANTREA_MULTICAST_IGMPQUERY_INTERVAL: "125s"
# ANTREA_TUNNEL_TYPE: geneve
# ANTREA_ENABLE_USAGE_REPORTING: false
# ANTREA_ENABLE_BRIDGING_MODE: false
# ANTREA_DISABLE_TXCHECKSUM_OFFLOAD: false
# ANTREA_DNS_SERVER_OVERRIDE: ""
# ANTREA_MULTICLUSTER_ENABLE: false
# ANTREA_MULTICLUSTER_NAMESPACE: ""
